version: '3.7'
services:
  nginx-a:
    image: nginx
    volumes:
      - ./a.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9898:80
    deploy:
      replicas: 3
  nginx-b:
    image: nginx
    volumes:
      - ./b.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 5
  nginx-c:
    ports:
      - 9097:80
    image: nginx
    volumes:
      - ./c.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 8
  nginx-d:
    image: nginx
    volumes:
      - ./d.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 4
      